* OdeToFood
  This git repo contains software as developed in the course
  [[https://www.pluralsight.com/courses/aspnet-core-fundamentals][ASP.NET Core Fundamentals by Scott Allen on pluralsight.com]].

  OdeToFood.Core and OdeToFood.Data projects are in separate
  repositories. See notes section at the end of this document.
* My development setup
  - Debian GNU/Linux Buster (10) on an Intel laptop
  - .NET Core 3.1
  - VS Code for writing C#
  - Emacs for taking notes
* Todo items
  - [ ] Convert this org file to markdown with pandoc
  - [ ] Create notes file
* Notes
** Added List razor page with the following command:
   dotnet-aspnet-codegenerator razorpage List Empty -udl -outDir Pages/Restaurants/
** Added libman tool with the following command:
   dotnet tool install -g Microsoft.Web.LibraryManager.Cli

   libman is used to install font-awesome library from cdnjs
** Above tools are also available as standalone commands
   After installing tools globally with dotnet tool install you can
   find them in ~/.dotnet/tools/. I placed symbolic links in my ~/bin/
   directory.
** Install font-awesome library with the following command
   libman install font-awesome

   Give this command in the project root
** OdeToFood.Core and OdeToFood.Data
   You als need to clone these repositories in order to start this
   web application.

   [[https://github.com/cuttlefish337/OdeToFood.Core][OdeToFood.Core]]
   [[https://github.com/cuttlefish337/OdeToFood.Data][OdeToFood.Data]]
