* OdeToFood
  This git repo contains software as developed in the course
  [[https://www.pluralsight.com/courses/aspnet-core-fundamentals][ASP.NET Core Fundamentals by Scott Allen on pluralsight.com]].

  OdeToFood.Core and OdeToFood.Data projects are in separate
  repositories. See notes section at the end of this document.
* My development setup
  - [[https://www.debian.org/][Debian GNU/Linux Buster (10)]]
  - [[https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-debian10][.NET Core 3.1]]
  - [[https://code.visualstudio.com/][VS Code for writing C#]]
  - [[https://www.mozilla.org/en-US/firefox/new/][Firefox]]
  - [[https://www.gnu.org/software/emacs/][Emacs]] with [[https://orgmode.org/][org-mode]] for taking notes
* Todo items
  - [ ] Convert this org file to markdown with pandoc
  - [ ] Create notes file
  - [ ] Merge OdeToFood.Core, OdeToFood.Data and OdeToFood into one
    repository
  - [ ] Fetching Restaurants by ID
* Notes
** Added List razor page with the following command:
   dotnet-aspnet-codegenerator razorpage List Empty -udl -outDir Pages/Restaurants/
** Added libman tool with the following command:
   dotnet tool install -g Microsoft.Web.LibraryManager.Cli

   libman is used to install font-awesome library from cdnjs
** Above tools are also available as standalone commands
   After installing tools globally with dotnet tool install you can
   find them in ~/.dotnet/tools/. I placed symbolic links in my ~/bin/
   directory.
** Install font-awesome library with the following command
   libman install font-awesome

   Give this command in the project root
** Chapter 3 Working with Models and Model Binding
*** Clip Binding to a Query String
    Use the following code from [[https://github.com/OdeToCode/OdeToFood/blob/master/OdeToFood/OdeToFood/Pages/Restaurants/List.cshtml][Scott's githubpage]]

    Modify it like this:
    #+BEGIN_SRC
<form method="get">
    <div class="form-group">
        <div class="input-group">
            <input type="search" class="form-control" value=""
                   name="searchTerm" />
            <span>
                <button class="btn btn-default">
                    <i class="fas fa-search"></i>
                </button>
            </span>
        </div>
    </div>
</form>
    #+END_SRC
** OdeToFood.Core and OdeToFood.Data
   You als need to clone these repositories in order to start this
   web application.

   [[https://github.com/cuttlefish337/OdeToFood.Core][OdeToFood.Core]]
   [[https://github.com/cuttlefish337/OdeToFood.Data][OdeToFood.Data]]
